kind: pipeline
name: surya

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: compile
    image: debian:buster
    environment:
      BOTTOKEN:
        from_secret: token
      USERCHATID:
        from_secret: chatid
    commands:
      - apt update && apt-get install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu abootimg python-is-python3
      - git clone --depth=1 https://github.com/JIaxyga/edk2-surya.git -b main && cd edk2-surya
      - chmod +x build_common.sh suryabuild.sh
      - bash build_common.sh && bash surya build.sh
      - curl -F document=@surya_uefi.img "https://api.telegram.org/bot$BOTTOKEN/sendDocument" -F chat_id="$USERCHATID" -F caption="$(date)"
